main: pluginmadness.PluginMadness
name: KingsPlugin
version: 1.0
author: 24Kings
api-version: 1.16

commands:
  scaffold:
    description: Enables ice boat scaffolding

  thor:
    description: You are the god of thuder!
    permission: pluginmadness.thor

  funni:
    description: Does the big funny
    permission: pluginmadness.funni

permissions:
  pluginmadness.funni:
    default: op
  pluginmadness.thor:
    default: op